use std::error::Error;

async fn main() -> Result<(), Box<dyn Error>> {
    Ok(())
}
